version: "3.9"
services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: pruebas
      POSTGRES_PASSWORD: postgres

    ports:
      - 5432:5432

    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_frases
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: mypassword
      PGADMIN_DATABASE: mydatabase

    ports:
      - 8080:80
